---

- hosts: all
  become: true
  tasks:

  - name: update index repository & install apache, php packages
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
